@startuml
title Relationships - Class Diagram

class Account {
    +Text FullName    
}

class Project {
    +Text Title
    +Bool ShowCompletedTasks
}

class AccountProject {
    +Account Account
    +Project Project
    +Bool IsAccepted
    +Bool IsOwner
}

class AccountTask {
    +Account Account
    +Task Task
    +Bool IsAccepted
}


class Task {
    +Text Title
    +Bool IsDone
    +Bool IsMyDay
    +Bool IsImportant
    +DateTime? RemindDate
    +Date? DueDate
    +RepeatType Repeat
    +Byte? SelectedWeekDay
    +Text Note
}

class Step {
    +Text Title
    +Bool Done
}

class File {
    +Text Filename
}

enum RepeatType{
    Daily
    Weekdays
    Weekly
    Monthly
    Yearly
}

Account "1" *-down- "1..many" AccountProject
Project "1" *-up- "1..many" AccountProject

Account "1" *-down- "0..many" AccountTask
Task    "1" *-up- "0..many" AccountTask

Project "1" *-down- "0..many" Task

Task "1" *-down- "0..many" File
Task "1" *-down- "0..many" Step
Task -> RepeatType

@enduml
