@startuml
title Relationships - Class Diagram

class Account {
    +Text FullName    
}

class Project {
    +Text Title
    +Bool ShowCompletedTasks
}

class SharedAccount {
    +Account ShareWithAccount
    +Bool IsAccepted
}

class Task {
    +Account AssignedTo
    +Text Title
    +Bool Done
    +Bool MyDay
    +Bool Important
    +DateTime? RemindDate
    +Date? DueDate
    +RepeatType Repeat
    +Byte? SelectedWeekDay
    +Text Note
    +Account? AssignedTo 
}

class Step {
    +Text Title
    +Bool Done
}

class File {
    +Text Filename
}

enum RepeatType{
    Daily
    Weekdays
    Weekly
    Monthly
    Yearly
}

Account "1" *-down- "many" Project
Project "1" *-down- "0..many" Task
Project "1" *-down- "0..many" SharedAccount
Account "1" *-down- "1" Task
Task "1" *-down- "0..many" File
Task "1" *-down- "0..many" Step
Task -> RepeatType
SharedAccount -> Account

@enduml
